### ISSUE TITLE
Receive following Error on Asp.net Core 5

### ISSUE THREAD

**Issue by christopher192** [iozcelik/EntityFrameworkCore.SqlServer.JsonExtention#1]
TypeLoadException: Method 'Translate' in type 'EntityFrameworkCore.SqlServer.JsonExtention.JsonTranslator' from assembly 'EntityFrameworkCore.SqlServer.JsonExtention, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by iozcelik** [comment]
@christopher192 I update project to .Net 6. I pass .Net 5 because of it is not long term support. After .Net 6, entity framework has native json support.
